name: Validate code

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: yarn
        working-directory: ./core
        run: yarn --frozen-lockfile
      # - name: Typescript check
      #   uses: EPMatt/reviewdog-action-tsc@v1
      #   with:
      #     # Change reviewdog reporter if you need
      #     # [github-pr-check,github-check,github-pr-review].
      #     # More about reviewdog reporters at
      #     # https://github.com/reviewdog/reviewdog#reporters
      #     reporter: github-check
      #     # Change reporter level if you need
      #     # [info,warning,error].
      #     # More about reviewdog reporter level at
      #     # https://github.com/reviewdog/reviewdog#reporters
      #     level: warning
      #     workdir: core
      # - name: Typescript strict plugin check
      #   run: yarn typecheck

      # - name: Tests
      #   run: yarn test:ci

      - name: Build
        working-directory: ./core
        run: yarn build
      - name: yarn
        working-directory: ./cli
        run: yarn --frozen-lockfile
      - name: Typescript strict plugin check
        working-directory: ./cli
        run: yarn typecheck
      - name: Typescript check
        uses: EPMatt/reviewdog-action-tsc@v1
        with:
          # Change reviewdog reporter if you need
          # [github-pr-check,github-check,github-pr-review].
          # More about reviewdog reporters at
          # https://github.com/reviewdog/reviewdog#reporters
          reporter: github-check
          # Change reporter level if you need
          # [info,warning,error].
          # More about reviewdog reporter level at
          # https://github.com/reviewdog/reviewdog#reporters
          level: warning
          workdir: cli
