name: Validate

on: [ pull_request ]

jobs:
  validate:
    name: Validate typescript
    uses: bratislava/github-actions/.github/workflows/validate-typescript.yml@stable
    with:
      workdir: '.'

  typescript-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: yarn --frozen-lockfile

      - name: Tests
        run: yarn test:ci

